// TA-CNT-006 -- ported chord-progression templates.
//
// Source: ldrolez/free-midi-chords, chords.py (prog_maj, prog_min lists).
// https://github.com/ldrolez/free-midi-chords -- MIT licence.
// Ported 2026-09-04: Roman-numeral degree/quality token sequences and their
// mood tags are copied verbatim as text data. No MIDI files, audio, or note
// data from that repository are used -- the actual chord voicings/pitches
// are generated by this codebase's own interval-formula engine in
// chordCatalogue.ts. See content/licences.json ("free-midi-chords-progressions").
//
// prog_modal (chromatic/borrowed-degree progressions such as bIII, #IV) was
// deliberately not ported -- out of scope for this pass.

export interface ProgressionTemplate {
  readonly tokens: readonly string[];
  readonly moods: readonly string[];
}

// 50 major-key progressions.
export const MAJOR_PROGRESSION_TEMPLATES: readonly ProgressionTemplate[] = [
  { tokens: ["I", "I", "IM-5", "IM-5", "IV", "IV", "V", "Vsus2"], moods: ["Joyful", "Triumphant"] },
  { tokens: ["I", "I", "IV", "iii"], moods: ["Hopeful", "Nostalgic"] },
  { tokens: ["I", "I7", "Idom7", "I7"], moods: ["Relaxed", "Playful"] },
  { tokens: ["I", "I7", "Idom7", "IV"], moods: ["Relaxed", "Nostalgic"] },
  { tokens: ["I", "iii", "IV", "vi"], moods: ["Romantic", "Nostalgic"] },
  { tokens: ["I", "iii", "vi", "Isus4"], moods: ["Tender", "Spiritual"] },
  { tokens: ["I", "iii", "vi", "IV"], moods: ["Romantic", "Hopeful"] },
  { tokens: ["I", "IV", "ii", "V"], moods: ["Joyful", "Triumphant"] },
  { tokens: ["I", "IV", "Isus2", "IV"], moods: ["Peaceful", "Hopeful"] },
  { tokens: ["I", "IV", "V", "IV"], moods: ["Joyful", "Triumphant"] },
  { tokens: ["I", "IV", "V"], moods: ["Joyful", "Excited"] },
  { tokens: ["I", "IV", "vi", "V"], moods: ["Joyful", "Hopeful"] },
  { tokens: ["I", "IV", "vii", "iii", "vi", "ii", "V", "I"], moods: ["Romantic", "Triumphant"] },
  { tokens: ["I", "V", "I", "IV"], moods: ["Joyful", "Playful"] },
  { tokens: ["I", "V", "IV", "vi"], moods: ["Romantic", "Hopeful"] },
  { tokens: ["I", "V", "vi", "ii"], moods: ["Hopeful", "Romantic"] },
  { tokens: ["I", "V", "vi", "iii", "IV", "I", "IV", "V"], moods: ["Hopeful", "Joyful"] },
  { tokens: ["I", "V", "vi", "iii", "IV"], moods: ["Hopeful", "Joyful"] },
  { tokens: ["I", "V", "vi", "IV"], moods: ["Hopeful", "Romantic"] },
  { tokens: ["I", "V", "vi", "V"], moods: ["Hopeful", "Romantic"] },
  { tokens: ["I", "vi", "I", "IV"], moods: ["Tender", "Nostalgic"] },
  { tokens: ["I", "vi", "ii", "IV"], moods: ["Tender", "Nostalgic"] },
  { tokens: ["I", "vi", "ii", "V"], moods: ["Nostalgic", "Romantic"] },
  { tokens: ["I", "vi", "IV", "iii"], moods: ["Nostalgic", "Romantic"] },
  { tokens: ["I", "vi", "IV", "V"], moods: ["Romantic", "Hopeful"] },
  { tokens: ["I7", "V7", "viadd9", "IV7"], moods: ["Playful", "Joyful"] },
  { tokens: ["ii", "IV", "V"], moods: ["Hopeful"] },
  { tokens: ["ii", "IV", "vi", "V"], moods: ["Romantic"] },
  { tokens: ["ii", "V", "I"], moods: ["Triumphant"] },
  { tokens: ["ii", "V", "I", "IV"], moods: ["Hopeful", "Triumphant"] },
  { tokens: ["ii7", "Vadd9", "I7"], moods: ["Triumphant"] },
  { tokens: ["iii", "vi", "IV", "I"], moods: ["Romantic", "Nostalgic"] },
  { tokens: ["iim7", "V7", "iiim7", "vi7", "iim7", "V7"], moods: ["Romantic", "Nostalgic"] },
  { tokens: ["Isus2", "I", "vi7", "visus4"], moods: ["Playful", "Romantic"] },
  { tokens: ["IV", "I", "ii", "vi"], moods: ["Nostalgic", "Peaceful"] },
  { tokens: ["IV", "I", "iii", "IV"], moods: ["Playful", "Joyful"] },
  { tokens: ["IV", "I", "IV6", "Iadd9"], moods: ["Relaxed", "Joyful"] },
  { tokens: ["IV", "I", "V", "vi"], moods: ["Joyful", "Romantic"] },
  { tokens: ["IV", "IV", "I", "V"], moods: ["Joyful", "Hopeful"] },
  { tokens: ["IV", "vi", "I", "V"], moods: ["Hopeful", "Romantic"] },
  { tokens: ["IV", "vi", "iii", "I"], moods: ["Nostalgic", "Playful"] },
  { tokens: ["IV", "vi", "IV", "vi"], moods: ["Nostalgic"] },
  { tokens: ["V", "I", "vi", "V"], moods: ["Hopeful", "Romantic"] },
  { tokens: ["V", "IV", "vi", "I"], moods: ["Hopeful", "Triumphant"] },
  { tokens: ["V", "vi", "IV", "I"], moods: ["Hopeful", "Romantic"] },
  { tokens: ["vi", "ii", "V", "I"], moods: ["Hopeful", "Romantic"] },
  { tokens: ["vi", "IV", "I", "V"], moods: ["Hopeful", "Romantic"] },
  { tokens: ["vi", "IV", "iii", "V"], moods: ["New", "Hopeful", "Romantic"] },
  { tokens: ["vi", "V", "IV", "V", "ii", "V", "I", "I"], moods: ["Triumphant", "Hopeful"] },
  { tokens: ["vi", "V", "IV", "V"], moods: ["Romantic", "Hopeful"] },
];

// 58 minor-key progressions.
export const MINOR_PROGRESSION_TEMPLATES: readonly ProgressionTemplate[] = [
  { tokens: ["i", "i", "iv", "iv", "v7", "ii5", "v", "v7"], moods: ["Dark", "Mysterious"] },
  { tokens: ["i", "ii", "v", "i"], moods: ["Mysterious", "Triumphant"] },
  { tokens: ["i", "III", "iv", "VI"], moods: ["Nostalgic", "Romantic"] },
  { tokens: ["i", "III", "VII", "iv"], moods: ["New", "Empowered", "Nostalgic"] },
  { tokens: ["i", "III", "VII", "VI"], moods: ["Nostalgic", "Romantic"] },
  { tokens: ["i", "ii", "v", "III", "i", "ii", "v", "VII"], moods: ["Mysterious", "Dramatic"] },
  { tokens: ["i", "iv", "III", "VI"], moods: ["Nostalgic", "Romantic"] },
  { tokens: ["i", "iv", "v", "iv"], moods: ["Mysterious", "Sad"] },
  { tokens: ["i", "iv", "v"], moods: ["Sad", "Lonely"] },
  { tokens: ["i", "iv", "VI", "v"], moods: ["Sad", "Hopeful"] },
  { tokens: ["i", "iv", "VII", "i"], moods: ["Sad", "Nostalgic"] },
  { tokens: ["i", "iv", "VII", "v", "i", "i", "ii", "V"], moods: ["Mysterious", "Surprised"] },
  { tokens: ["i", "v", "iv", "VII"], moods: ["Sad", "Rebellious"] },
  { tokens: ["i", "vdim", "iv", "VI"], moods: ["Dark", "Nostalgic"] },
  { tokens: ["i", "VI", "III", "VII", "i", "VI69", "III7", "VII"], moods: ["Mysterious", "Spiritual"] },
  { tokens: ["i", "VI", "III", "VII"], moods: ["Nostalgic", "Hopeful"] },
  { tokens: ["i", "VI", "iv", "ii"], moods: ["Sad", "Tender"] },
  { tokens: ["i", "VI", "iv", "III"], moods: ["Sad", "Nostalgic"] },
  { tokens: ["i", "VI", "iv", "v"], moods: ["Sad", "Hopeful"] },
  { tokens: ["i", "VI", "VII", "iv"], moods: ["Mysterious", "Nostalgic"] },
  { tokens: ["i", "VI", "VII", "v"], moods: ["Mysterious", "Rebellious"] },
  { tokens: ["i", "VI", "VII"], moods: ["Triumphant", "Rebellious"] },
  { tokens: ["i", "VII", "i", "v", "III", "VII", "i", "v", "i"], moods: ["Mysterious", "Surprised"] },
  { tokens: ["i", "VII", "i", "v"], moods: ["Mysterious", "Nostalgic"] },
  { tokens: ["i", "VII", "III", "VI"], moods: ["Rebellious", "Triumphant"] },
  { tokens: ["i", "VII", "v", "VI"], moods: ["Mysterious", "Hopeful"] },
  { tokens: ["i", "VII", "VI", "III", "iv", "VI", "VII", "i"], moods: ["Mysterious", "Surprised"] },
  { tokens: ["i", "VII", "VI", "III"], moods: ["Nostalgic", "Hopeful"] },
  { tokens: ["i", "VII", "VI", "iv"], moods: ["Sad", "Romantic"] },
  { tokens: ["i", "VII", "VI", "VII"], moods: ["Rebellious", "Triumphant"] },
  { tokens: ["i", "VII", "VIadd9", "VII", "i", "v", "VI", "VIIsus4"], moods: ["New", "Nostalgic", "Sad"] },
  { tokens: ["i7", "VI", "III7", "VII6", "i", "i7", "III7", "iv7"], moods: ["Dark", "Nostalgic"] },
  { tokens: ["i7", "VII", "VI7", "iv7"], moods: ["Nostalgic", "Romantic"] },
  { tokens: ["ii", "v", "i"], moods: ["Peaceful", "Hopeful"] },
  { tokens: ["ii", "v", "i", "iv"], moods: ["Peaceful", "Nostalgic"] },
  { tokens: ["ii", "VI", "i", "iv"], moods: ["Sad", "Hopeful"] },
  { tokens: ["im7", "ivsus4", "v7", "isus4"], moods: ["Mysterious", "Tender"] },
  { tokens: ["iv", "i", "v", "VI"], moods: ["Nostalgic", "Hopeful"] },
  { tokens: ["iv", "III", "VII", "i"], moods: ["Nostalgic", "Mysterious"] },
  { tokens: ["iv", "III", "vsus4", "VI", "iv", "i", "III", "VI"], moods: ["Nostalgic", "Mysterious"] },
  { tokens: ["iv", "v", "VI", "VII"], moods: ["Mysterious", "Rebellious"] },
  { tokens: ["iv", "VI", "v", "VII"], moods: ["Mysterious", "Hopeful"] },
  { tokens: ["iv", "VI", "VII", "i"], moods: ["Triumphant"] },
  { tokens: ["v", "i", "iv", "VII"], moods: ["Dark", "Rebellious"] },
  { tokens: ["v", "iv", "i"], moods: ["Lonely"] },
  { tokens: ["v", "VI", "III", "i"], moods: ["Hopeful", "Nostalgic"] },
  { tokens: ["v", "VI", "v", "i"], moods: ["Sad"] },
  { tokens: ["VI", "i", "v", "III"], moods: ["Hopeful", "Nostalgic"] },
  { tokens: ["VI", "i", "v"], moods: ["Sad"] },
  { tokens: ["VI", "III", "i", "v"], moods: ["Nostalgic", "Dark"] },
  { tokens: ["VI", "iv", "i", "v"], moods: ["Hopeful", "Tender"] },
  { tokens: ["VI", "VI", "i", "VII"], moods: ["Empowered"] },
  { tokens: ["VI", "VII", "i", "III"], moods: ["Triumphant", "Nostalgic"] },
  { tokens: ["VI", "VII", "v", "III"], moods: ["Rebellious", "Nostalgic"] },
  { tokens: ["VI7", "VII", "i", "v", "VI7", "VII", "i", "iv7"], moods: ["New", "Empowered", "Nostalgic"] },
  { tokens: ["VI7", "VII6", "i", "VII6"], moods: ["New", "Nostalgic", "Hopeful"] },
  { tokens: ["VII", "iv", "v", "i"], moods: ["Mysterious", "Dark"] },
  { tokens: ["VII", "iv", "VII", "i"], moods: ["Spiritual"] },
];

